// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7BOmJrw_Fiqvng-nWgW4ZGxm7UTzSicI',
    appId: '1:432527601160:web:11e6fc7b36d99b09732bbd',
    messagingSenderId: '432527601160',
    projectId: 'contact-trace-2025-f636f',
    authDomain: 'contact-trace-2025-f636f.firebaseapp.com',
    storageBucket: 'contact-trace-2025-f636f.firebasestorage.app',
    measurementId: 'G-1D5KLL42V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj9iWN4LycgtepqYxvist1wNIe0ujdECk',
    appId: '1:432527601160:android:e3a9c324cb9aa00b732bbd',
    messagingSenderId: '432527601160',
    projectId: 'contact-trace-2025-f636f',
    storageBucket: 'contact-trace-2025-f636f.firebasestorage.app',
  );
}
